/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthArticlesRouteImport } from './routes/_auth.articles'
import { Route as AuthArticlesIndexRouteImport } from './routes/_auth.articles.index'
import { Route as AuthArticlesCreateRouteImport } from './routes/_auth.articles.create'
import { Route as AuthArticlesArticleIdRouteImport } from './routes/_auth.articles.$articleId'
import { Route as AuthArticlesArticleIdEditRouteImport } from './routes/_auth.articles.$articleId.edit'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthArticlesRoute = AuthArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => AuthRoute,
} as any)
const AuthArticlesIndexRoute = AuthArticlesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthArticlesRoute,
} as any)
const AuthArticlesCreateRoute = AuthArticlesCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AuthArticlesRoute,
} as any)
const AuthArticlesArticleIdRoute = AuthArticlesArticleIdRouteImport.update({
  id: '/$articleId',
  path: '/$articleId',
  getParentRoute: () => AuthArticlesRoute,
} as any)
const AuthArticlesArticleIdEditRoute =
  AuthArticlesArticleIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthArticlesArticleIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/articles': typeof AuthArticlesRouteWithChildren
  '/articles/$articleId': typeof AuthArticlesArticleIdRouteWithChildren
  '/articles/create': typeof AuthArticlesCreateRoute
  '/articles/': typeof AuthArticlesIndexRoute
  '/articles/$articleId/edit': typeof AuthArticlesArticleIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/articles/$articleId': typeof AuthArticlesArticleIdRouteWithChildren
  '/articles/create': typeof AuthArticlesCreateRoute
  '/articles': typeof AuthArticlesIndexRoute
  '/articles/$articleId/edit': typeof AuthArticlesArticleIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_auth/articles': typeof AuthArticlesRouteWithChildren
  '/_auth/articles/$articleId': typeof AuthArticlesArticleIdRouteWithChildren
  '/_auth/articles/create': typeof AuthArticlesCreateRoute
  '/_auth/articles/': typeof AuthArticlesIndexRoute
  '/_auth/articles/$articleId/edit': typeof AuthArticlesArticleIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/articles'
    | '/articles/$articleId'
    | '/articles/create'
    | '/articles/'
    | '/articles/$articleId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/articles/$articleId'
    | '/articles/create'
    | '/articles'
    | '/articles/$articleId/edit'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/register'
    | '/_auth/articles'
    | '/_auth/articles/$articleId'
    | '/_auth/articles/create'
    | '/_auth/articles/'
    | '/_auth/articles/$articleId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/articles': {
      id: '/_auth/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof AuthArticlesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/articles/': {
      id: '/_auth/articles/'
      path: '/'
      fullPath: '/articles/'
      preLoaderRoute: typeof AuthArticlesIndexRouteImport
      parentRoute: typeof AuthArticlesRoute
    }
    '/_auth/articles/create': {
      id: '/_auth/articles/create'
      path: '/create'
      fullPath: '/articles/create'
      preLoaderRoute: typeof AuthArticlesCreateRouteImport
      parentRoute: typeof AuthArticlesRoute
    }
    '/_auth/articles/$articleId': {
      id: '/_auth/articles/$articleId'
      path: '/$articleId'
      fullPath: '/articles/$articleId'
      preLoaderRoute: typeof AuthArticlesArticleIdRouteImport
      parentRoute: typeof AuthArticlesRoute
    }
    '/_auth/articles/$articleId/edit': {
      id: '/_auth/articles/$articleId/edit'
      path: '/edit'
      fullPath: '/articles/$articleId/edit'
      preLoaderRoute: typeof AuthArticlesArticleIdEditRouteImport
      parentRoute: typeof AuthArticlesArticleIdRoute
    }
  }
}

interface AuthArticlesArticleIdRouteChildren {
  AuthArticlesArticleIdEditRoute: typeof AuthArticlesArticleIdEditRoute
}

const AuthArticlesArticleIdRouteChildren: AuthArticlesArticleIdRouteChildren = {
  AuthArticlesArticleIdEditRoute: AuthArticlesArticleIdEditRoute,
}

const AuthArticlesArticleIdRouteWithChildren =
  AuthArticlesArticleIdRoute._addFileChildren(
    AuthArticlesArticleIdRouteChildren,
  )

interface AuthArticlesRouteChildren {
  AuthArticlesArticleIdRoute: typeof AuthArticlesArticleIdRouteWithChildren
  AuthArticlesCreateRoute: typeof AuthArticlesCreateRoute
  AuthArticlesIndexRoute: typeof AuthArticlesIndexRoute
}

const AuthArticlesRouteChildren: AuthArticlesRouteChildren = {
  AuthArticlesArticleIdRoute: AuthArticlesArticleIdRouteWithChildren,
  AuthArticlesCreateRoute: AuthArticlesCreateRoute,
  AuthArticlesIndexRoute: AuthArticlesIndexRoute,
}

const AuthArticlesRouteWithChildren = AuthArticlesRoute._addFileChildren(
  AuthArticlesRouteChildren,
)

interface AuthRouteChildren {
  AuthArticlesRoute: typeof AuthArticlesRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthArticlesRoute: AuthArticlesRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
